// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGMeLQB0b5TLjXRfYpsKidlZIAQcaNgsw',
    appId: '1:676835115838:web:20cb635197f0d8c43be26f',
    messagingSenderId: '676835115838',
    projectId: 'docdoc-app-9e8b8',
    authDomain: 'docdoc-app-9e8b8.firebaseapp.com',
    storageBucket: 'docdoc-app-9e8b8.appspot.com',
    measurementId: 'G-J16HR3FEEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoltef_zFTEcJ-vWPlwdiDsUYsmqhaYIo',
    appId: '1:676835115838:android:a128cda29a12b4013be26f',
    messagingSenderId: '676835115838',
    projectId: 'docdoc-app-9e8b8',
    storageBucket: 'docdoc-app-9e8b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1wCnmIO2ml63kRLjwcReRZ0_f_C4CJio',
    appId: '1:676835115838:ios:b68214143d036a893be26f',
    messagingSenderId: '676835115838',
    projectId: 'docdoc-app-9e8b8',
    storageBucket: 'docdoc-app-9e8b8.appspot.com',
    iosBundleId: 'com.example.appointmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1wCnmIO2ml63kRLjwcReRZ0_f_C4CJio',
    appId: '1:676835115838:ios:b68214143d036a893be26f',
    messagingSenderId: '676835115838',
    projectId: 'docdoc-app-9e8b8',
    storageBucket: 'docdoc-app-9e8b8.appspot.com',
    iosBundleId: 'com.example.appointmentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGMeLQB0b5TLjXRfYpsKidlZIAQcaNgsw',
    appId: '1:676835115838:web:eeb66965ee3c1c473be26f',
    messagingSenderId: '676835115838',
    projectId: 'docdoc-app-9e8b8',
    authDomain: 'docdoc-app-9e8b8.firebaseapp.com',
    storageBucket: 'docdoc-app-9e8b8.appspot.com',
    measurementId: 'G-3FF3HWV4YC',
  );
}
